name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean install

    - name: Trigger Jenkins deployment
      run: curl -X POST https://52fb-2405-201-4062-702c-80e6-cabb-3fae-846b.ngrok-free.app/job/insured-assurance-deploy/build?token=deploy123

